#!/usr/bin/env bash
# Installs and configures HAProxy for round-robin load balancing

apt-get -y update
apt-get -y install haproxy

cat << INNER_EOF >> /etc/haproxy/haproxy.cfg
frontend my_frontend
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web-01 10.0.0.1:80 check
    server web-02 32.197.226.90:80 check
INNER_EOF

service haproxy restart
