#!/usr/bin/env bash
# Installs and configures HAProxy for round-robin load balancing

apt-get -y update
apt-get -y install haproxy

cat << 'CONFIG' > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend my_frontend
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 44.203.202.93:80 check
    server web-02 32.197.226.90:80 check
CONFIG

service haproxy restart
