#!/usr/bin/env bash
# Configures Nginx server to redirect /redirect_me to a YouTube video

apt-get -y update
apt-get -y install nginx

# Use sed to add the redirect rule into the default Nginx config
sed -i '/server_name _;/a \ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
