#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page

apt-get -y update
apt-get -y install nginx

# Create the custom HTML page with the required string
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Use sed to add the error_page directive to the default Nginx config
sed -i '/server_name _;/a \ \terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

service nginx restart
